

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gestorvendas_sqlserver
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"${SA_PASSWORD}\" -C -Q 'SELECT 1' > /dev/null 2>&1 || /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"${SA_PASSWORD}\" -Q 'SELECT 1' > /dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 5

  flyway:
    image: flyway/flyway:latest
    container_name: gestorvendas_flyway_migrations
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./sql:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:sqlserver://sqlserver:1433;databaseName=MeuBanco;encrypt=true;trustServerCertificate=true;
      - FLYWAY_USER=sa
      - FLYWAY_PASSWORD=${SA_PASSWORD}
      - FLYWAY_CONNECT_RETRIES=60
    command: migrate


volumes:
  sqlserver-data:
