CREATE FUNCTION dbo.fn_hash_cpf (@cpf VARCHAR(60))
RETURN VARCHAR(60)
AS
BEGIN
    DECLARE @Salt VARCHAR(50) = 'ChaveSecretadoVillaGuiné'

    DECLARE @HashBi VARBINARY(32) = HASHBYTES('SHA2_256', CONCAT(@cpf,@Salt));

    RETURN LEFT(CONVERT(VARCHAR(64), @HashBi, 2), 60);
END;

